FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN python -m nltk.downloader punkt

COPY . .

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "80"]